var strings = {
  ar: {
    FAV_LANG: "اللغة",
    FAV_LANGUAGE: "تغيير اللغة",
    SHOPPING_CART: "عربة التسوق",
    SR: "ر.س",
    TOTAL_PRODUCTS: "إجمالي المنتجات",
    THERE_ARE_NO_PRODUCTS_IN_THE_SHOPPING_CART:
      "لا يوجد منتجات في سلة المشتريات",
    FIRST_ITHOOB_CLOTH: "ثوب أيتوب الأول",
    GO_TO_PAY: "الذهاب إلى الدفع",
    TO_THE_SHOPPING_CART: "إلى عربة التسوق",
    BACK_TO_THE_SHOPPING_CART: "عودة إلى عربة التسوق",
    MAIN: "الرئيسية",
    PAYMENT_AND_RECEIPT: "الدفع و الاستلام",
    PAYMENT: "الدفع",
    CONFIRMATION: "تأكيد الطلب",
    ARE_YOU_SURE_YOU_WANT_TO_COMPLETE_THE_REQUEST:
      "هل أنت متأكد أنك تريد إتمام الطلب؟",
    YES_COMPLETE_THE_ORDER: "نعم استكمل الطلب",
    NO: "لا",
    DELIVERY_METHOD: "طريقه التوصيل",
    PAYMENT_METHOD: "طريقه الدفع",
    DELIVERY_TO_HOME: "التوصيل إلى المنزل",
    RECEIVING_FROM_BRANCH: "الاستلام من الفرع",
    ADDRESS: "العنوان",
    BRANCH_DETAILS: "تفاصيل الفرع",
    BRANCH_ADDRESS: "عنوان الفرع",
    WORKING_HOURS_BRANCH: "مواعيد العمل بالفرع",
    BRANCH_NUMBER: "رقم الفرع",
    YOUR_ORDER_NUMBER: "طلبك رقم",
    DONE_SUCCESSFULLY: "تم بنجاح",
    YOU_WILL_BE_COMPLETED_REGISTER_YOUR_TEXT_MESSAGE_AFTER_TWO_DAYS:
      "سوف يتم إكمال تسجيل طلبك برسالة نصية بعد يومين",
    COMPLETE_SHOPPING: "أكمل التسوق",
    CONTINUED_REQUEST: "تابع طلبك",
    ORDER_SUMMARY: "ملخص الطلب",
    SHIPPING: "الشحن",
    YOU_WILL_DETERMINE_THE_COST_OF_SHIPPING_BASED_ON_YOUR_AREA_AND_YOUR_ADDRESS:
      "سوف تحدد تكلفة الشحن بناءً على منطقتك و عنوانك",
    PARTNERS_CODE: "كود الشركاء",
    I_HAVE_OBTAINED_A_DISCOUNT_VALUES: "لقد تحصلت على خصم بقيمة",
    HIGHEST_DISCOUNT_WILL_BE_APPLIED: "سيتم تطبيق قيمة الخصم الأعلى على طلبك",
    SHIPPING_IS_A_COMPREHENSIVE_AND_COST_TAILOR:
      "غير شامل الشحن و تكلفة الترزي",
    PERMANENT_DISCOUNT: "الخصم الدائم",
    PERMANENT_DISCOUNT_WORTH: "خصم دائم بقيمة",
    BEING_A_PERMANENT_PARTNERS_ANY_GOWN: "لكونك أحد شركاء آي ثوب",
    YOU_CAN_NOT_LEAVE_THE_TITLE_BOX_BLANK: "لا يمكنك ترك خانة العنوان فارغة.",
    NOT_AVAILABLE_ITEM: "هذا المنتج لم يعد متوفر حالياً. برجاء الحذف لتتمكن من استكمال الطلب.",
    THIS_PRODUCT_IS_SOLD_OUT: "هذا المنتج غير متوفر بالمخزون",
    THIS_PRODUCT_IS_OUT_OF_STOCK: "نفدت الكمية",
    THERE_IS_ONE_OR_MORE_UNAVAILABLE_ITEMS: "يبدو أن لديك منتجًا واحدًا أو أكثر غير متوفر",
    GO_TO_PAYMENT: "الذهاب إلى الدفع",
    BANK_TRANSFER: "التحويل البنكي",
    THE_ORDER_WILL_BE_CONFIRMED_TWO_DAYS_AFTER_THE_ARRIVAL_OF_THE_HAWALA_BANKING_US:
      "سوف يتم تأكيد الطلب بعد يومين من وصول الحوالة البنكية إلينا",
    ACCOUNT_NUMBER: "رقم حساب",
    THE_RECEIPT: "الاستلام",
    RECEIVING_DATE: "موعد الاستلام",
    YOUR_REQUEST_WILL_BE_READY_FOR_PICK_UP: "سيكون طلبك جاهز للاستلام",
    TAILOR: "الترزي",
    WILL_CALL_YOU_ONE_OF_OUR_REPRESENTATIVES_TO_SET_A_DATE_FOR_TAKING_MQASATK_HOME:
      "سيتصل بك أحد مندوبينا لتحديد موعد لأخذ مقاساتك بالمنزل",
    ANY_DRESS_IS_A_SAUDI_BRAND_GIVES_YOU_A_PROVEN_FACT_NAK_LONG_TIME_AGO_IS_THAT_THE_READABLE_CONTENT_OF_A_PAGE_SILAA_NATURALLY:
      "علامة تميز ثوب الرجل ليجمع بين الأناقة والأصالة",
    ITHOOB_RIGHTS_RESERVED: "الحقوق محفوظة iThoob 2020",
    JZL_RIGHTS_RESERVED: "الحقوق محفوظة iThoob 2020",
    CONNECT_WITH_US: "تواصل معنا",
    ABOUT_ITHOOB: "عن آي ثوب",
    ABOUT_JZL: "عن آي ثوب",
    MEASUREMENTS_TABLE: "جدول المقاسات",
    FAQ: "الأسئلة الأكثر شيوعا",
    PERSONAL_INFORMATION: "معلوماتي الشخصية",
    MEASUREMENTS: "مقاساتي",
    MY_ORDERS: "طلباتي",
    LOG_OUT: "تسجيل خروج",
    DESIGNED_YOUR_DRESS: "أطلب الخياط",

    LOG_IN: "تسجيل الدخول",
    YOU_MUST_ENTER_THE_NEW_PASSWORD: "يجب إدخال كلمة المرور الجديدة",
    THE_PASSWORD_YOU_ENTERED_IS_CAFE_MUST_BE_YOUR_PASSWORD_CONSISTING_OF_8_DIGITS_OR_LETTERS:
      "كلمة المرور التى أدخلتها غير كافيه, يجب أن تكون كلمة المرور مكونه من 8 أرقام أو أحرف",
    CHANGE_PASSWORD: "تغيير كلمة المرور",
    NEW_PASSWORD: "كلمة المرور الجديدة",
    COUNTRY: "الدولة",
    REGION: "المنطقة",
    ACCOUNT_SUCCESSFULLY_CREATED: "تم إنشاء الحساب بنجاح",
    YOU_ARE_A_PARTNER_OF_ANY_DISCERNING_DRESS_AND_SO_YOU_WILL_ENJOY_A_PERMANENT_DISCOUNT_TO_ANY_OF_THE_PRODUCTS_OF_ANY_DRESS_VALUES:
      "أنت أحد شركاء آي ثوب المميزين ولذلك سوف تتمتع بخصم دائم على أي من منتجات آي ثوب بقيمة",
    START_SHOPPING_NOW: "إبدأ التسوق الآن",
    PLEASE_ENTER_YOUR_PASSWORD: "يرجى إدخال كلمة المرور",
    SHOULD_NOT_BE_LESS_THAN_THE_NUMBER_OF_CHARACTERS_NAME_3:
      "يجب ألا يقل عدد أحرف الاسم عن 3",
    PLEASE_WRITE_YOUR_CORRECT_EMAIL_AND_TRY_AGAIN:
      "نرجو كتابة البريد الكتروني الصحيح الخاص بك وإعادة المحاولة",
    EMAIL_SEEMS_SHORT_PLEASE_ENTER_A_VALID_EMAIL:
      "البريد الالكتروني يبدو قصير ... يرجى إدخال بريد الكتروني صحيح ---",
    PLEASE_ENTER_YOUR_PHONE_NUMBER: "يرجى إدخال رقم الجوال الخاص بك",
    THE_PHONE_NUMBER_IS_NOT_ENOUGH_PLEASE_ENTER_THE_NUMBERS_8_OR_MORE:
      "رقم الجوال غير كافي, يرجى إدخال 8 أرقام أو أكثر",
    PLEASE_ENTER_NUMBERS_ONLY: "يرجى إدخال أرقام فقط",
    CREATE_A_NEW_ACCOUNT: "إنشاء حساب جديد",
    FORGOT_YOUR_PASSWORD: "هل نسيت كلمة المرور؟",
    E_MAIL: "البريد الالكتروني",
    PASSWORD: "كلمة المرور",
    OPTIONAL: "اختياري",
    CREATE_ACCOUNT: "إنشاء حساب",
    THE_NAME: "الاسم",
    MOBILE: "الجوال",
    MOBILE_HINT: "مثال: 00966987654321",
    SIGN_IN_WITH_FACEBOOK: "دخول عبر فيسبوك",
    THIS_E_MAIL_IS_INCORRECT_PLEASE_MAKE_SURE_OF_IT_AND_TRY_AGAIN:
      "هذا البريد الالكتروني غير صحيح, يرجى التأكد منه و المحاولة مرة أخرى",
    PASSWORD_RECOVERY: "استرجاع كلمة المرور",
    CHANGE_PASSWORD_TEXT: "تغيير كلمة المرور",
    SIGN_IN_WITH_GOOGLE: "دخول عبر جوجل",
    RECOMMENDED: "موصى به",
    PLEASE_ENTER_THE_NUMBER_OR_YOUR_EMAIL:
      "يرجى إدخال الجوال أو البريد الالكتروني الخاص بك",
    EMAIL_FORMAT_IS_INCORRECT_MUST_BE_COORDINATION:
      "تنسيق البريد الالكتروني غير صحيح, يجب أن يكون التنسيق: example@example.com",
    NO_MOBILE_IS_INCOMPLETE: "رقم الموبيل غير كامل",
    EMAIL_IS_INCOMPLETE: "البريد الالكتروني غير كامل",
    THE_PASSWORD_IS_NOT_ENOUGH_MUST_BE_PASSWORD_COMPOSED_OF_8_DIGITS_OR_LETTERS:
      "كلمة المرور غير كافيه, يجب أن تكون كلمة المرور مكونه من 8 أرقام أو أحرف",
    DO_YOU_WANT_TO_SET_UP_AN_ACCOUNT_AND_RESTORE_ALL_MQASATK_AND_PREVIOUS_REQUESTS_HAVE_ANY_DRESS:
      "هل تريد إنشاء حساب و استعادة جميع مقاساتك و طلباتك السابقة لدى آي ثوب؟",
    YOU_DO_NOT_HAVE_AN_ACCOUNT_CREATE_AN_ACCOUNT: "ليس لديك حساب؟ إنضم الآن",
    SIZE: "المقاس",
    THIS_FILE_IS_INCOMPLETE_MUST_COMPLETE_THE_FILE_BEFORE_PURCHASE:
      "هذا الملف غير مكتمل .. يجب إكمال الملف قبل الشراء",
    ADD_FILE_FORMAT: "أضف ملف مقاسات",
    I_WANT_TO_TAKE_SIZE_TAILOR_HOME: "أريد أخذ المقاسات",
    THE_EXTRA_COST_STARTING_FROM: "تكلفة إضافية تبدأ من",
    BY_REGION: "حسب المنطقة",
    LOADING: "جار التحميل",
    
    BEST_SELLER: "الأكثر مبيعا",
    DRESS_DESIGNER: "ثوب مصمم",
    RATE: "معدل",
    SPECIAL_SIZE: "مقاس خاص",
    DO_NOT_CHOOSE_SIZE: "لم تقم باختيار مقاس",
    CHOOSE_SIZE: "اختر مقاس",
    I_WANT_TO_TARZI: "أريد أخذ المقاسات",
    MODIFY: "تعديل",
    CHANGING_THE_SIZE: "تغيير المقاس",
    DELETE: "حذف",
    ONE_PIECE: "القطعة الواحدة",
    EDIT_THE_DRESS: "عدل الثوب",
    DELETED: "تم حذف",
    SUCCESSFULLY_ADDED: "بنجاح",
    SUCCESSFULLY: "بنجاح",
    ARE_YOU_SURE_YOU_WANT_TO_DELETE: "هل أنت متأكد أنك تريد حذف",
    OF_YOUR_SHOPPING_CART: "من عربة التسوق الخاصة بك؟",
    YEAH: "نعم",
    EDIT_SIZE: "عدل المقاس",
    ANY_TOP_PARTNERS: "شركاء آي ثوب ",
    PARTNERS_SCHEDULE: "جدول الشركاء",
    USE_YOUR_COMPANY_EMAIL_TO_GET_PARTNER_DISCOUNT: "يرجى استخدام إيميل منشأتك لإرسال كود الخصم",
    ENTER: "أدخل",
    THE_COST_TAILOR: "تكلفة الترزي",
    YOU_WILL_DETERMINE_THE_COST_TARAZI_BASED_ON_YOUR_AREA_AND_YOUR_ADDRESS:
      "سوف تحدد تكلفة الترزي بناءً على منطقتك و عنوانك",
    DISCOUNT_PERCENTAGE: "نسبة الخصم",
    PARTNERS: "الشركاء",
    THE_MOST_COMMON_QUESTIONS: "أكثر الأسئلة شيوعا",
    ACCOUNT_SETTINGS: "أعدادات الحساب",
    MY_PROFILE: "معلوماتي الشخصية",
    YOU_MUST_FILL_IN_THE_PASSWORD: "يجب ملئ كلمة المرور",
    THE_NEW_PASSWORD_YOU_ENTERED_IS_CAFE_MUST_BE_YOUR_PASSWORD_CONSISTING_OF_8_DIGITS_OR_CHARACTERS:
      "كلمة المرور الجديدة التى أدخلتها غير كافيه. يجب أن تكون كلمة المرور مكونه من 8 أرقام أو أحرف",
    CURRENT_PASSWORD: "كلمة المرور الحالية",
    PASSWORD_CHANGED_SUCCESSFULLY: "تم تغيير كلمة المرور بنجاح",
    MY_PERSONAL: "معلوماتي الشخصية",
    BASIC_INFORMATION: "المعلومات الأساسية",
    PLEASE_ENTER_YOUR_NAME: "من فضلك أدخل الاسم",
    NAME_YOU_MUST_BE_BETWEEN_3_TO_50_CHARACTERS:
      "الاسم يجب أن يكون بين 3 إلى 50 حرف",
    DO_YOU_WANT_TO_CHANGE_YOUR_PASSWORD: "هل تريد تغيير كلمة المرور؟",
    PRESS_HERE: "تغيير",
    CONTACT_INFO: "معلومات التواصل",
    TITLE_OPTIONAL: "العنوان (اختياري)",
    TITLE_MUST_BE_BETWEEN_3_TO_100_CHARACTERS:
      "العنوان يجب أن يكون بين 20 إلى 100 حرف",
    YOUR_INFORMATION_HAS_BEEN_UPDATED_SUCCESSFULLY: " تم تحديث معلوماتك بنجاح",
    SAVING_INFORMATION: "حفظ المعلومات",
    THE_FIRST_DESIGNED_YOUR_DRESS: "صمم ثوبك الأول",
    ADD_TO_CART: "أضف إلى العربة",
    ADD_TO_CART_NOTIFICATION: "تم إضافة المنتج إلى العربة",
    THE_COLOR: "اللون",
    DRESS_ACCESSORIES: "إكسسوارات الثوب",
    A_MESSAGE_WAS_SENT_TO_YOUR_EMAIL: "تم إرسال رسالة إلى بريدك الالكتروني",
    A_MESSAGE_WAS_SENT_TO_YOUR_PHONE: "تم إرسال رسالة إلى جوالك",
    PLEASE_ENTER_THE_CODE_SENT_TO_YOUR_EMAIL_TO_COMPLETE_THE_REGISTRATION_PROCESS:
      "يرجى إدخال الكود الذى تم إرساله إلى بريدك الالكتروني لإكمال عملية التسجيل",
    PLEASE_ENTER_THE_CODE_SENT_TO_YOUR_PHONE_TO_COMPLETE_THE_REGISTRATION_PROCESS:
      "يرجى إدخال الكود الذى تم إرساله إلى جوالك لإكمال عملية التسجيل",
    SEND_CODE_AGAIN: "أرسل الكود مرة أخرى",
    CODE: "الكود",
    PLEASE_ENTER_THE_CODE_SENDER_PHONE: "يرجى إدخال الكود المرسل إلى جوالك",
    PLEASE_ENTER_THE_CODE_IN_FULL: "يرجى إدخال الكود كاملا",
    REGISTER_BY_EMAIL: "سجل عن طريق البريد الالكتروني",
    HAVE_AN_ACCOUNT_BEFORE: "لديك حساب؟ ",
    OR: "أو",
    QUANTITY: "الكمية",
    SHOP_NOW: "تسوق الان",
    VIEW_MORE: "عرض المزيد من",
    LATEST: "أحدث",
    RECOMMENDED_A: "موصى به",
    PRODUCT_DISPLAY: "عرض المنتج",
    SIZES_TABLE: "جدول المقاسات",
    //mai
    CONTACT_US: "راسلنا",
    THE_MESSAGE: "الرسالة",
    SEND: "إرسال",
    OH_PLEASE_ADD_YOUR_NAME: " الرجاء إضافة اسمك",
    OH_THIS_LOOKS_SO_SHORT_TO_BE_YOUR_NAME:
      "يا! هذا يبدو وقصيرة جدا ليكون اسمك",
    OH_PLEASE_ADD_A_VALID_EMAIL_ADDRESS:
      "يا! الرجاء إضافة عنوان بريد إلكتروني صالح.",
    OH_THIS_LOOKS_SO_SHORT_TO_BE_YOUR_EMAIL:
      "يا! هذا يبدو قصيرة جدا أن يكون البريد الالكتروني",
    OH_YOU_MOBILE_NUMBER_SHOULD_BE_ONLY_DIGITS:
      "يا! يجب أن تكون على رقم الجوال الوحيد أرقام.",
    OH_THIS_LOOKS_SO_SHORT_TO_BE_YOUR_MOBILE_NUMBER:
      "يا! هذا يبدو وقصيرة جدا ليكون رقم هاتفك المحمول",
    YOU_FORGET_TO_WRITE_YOUR_MESSAGE: "نسيت أن تكتب رسالتك",
    CANCELLING_ORDER: "إلغاء الطلب",
    MY_REQUESTS: "طلباتي",
    YOU_CAN_FOLLOW_YOUR_ORDERS_FROM_HERE: "يمكنك متابعة طلباتك من هنا",
    CURRENT_APPLICATIONS: "الطلبات الحالية",
    ALL_APPLICATIONS: "كل الطلبات",
    PREVIOUS_APPLICATIONS: "الطلبات السابقة",
    ORDERS_CANCELED: "الطلبات الملغية",
    APPLICATION_NO: "الطلب رقم",
    ORDER_CANCELED: "طلب ملغي",
    NEW_ORDER: "طلب جديد",
    PRODUCTION_STAGE: "مرحلة الإنتاج",
    DELIVERY: "التسليم",
    READY_BRANCH: "جاهز بالفرع",
    RECEIVED: "تم الاستلام",
    CHARGED: "تم الشحن",
    DETAILS: "تفاصيل الطلب",
    DISPLAY_ADJUSTMENTS: "عرض التعديلات",
    STARTS_FROM: "يبدا من",
    THE_TOTAL_EXPECTED: "الإجمالي المتوقع",
    SHIPPING__PAYMENT: "الشحن والدفع",
    PAYMENT_METHOD: "طريقة الدفع",
    SHIPPING_METHOD: "طريقة الشحن",
    NOT_ANY_REQUESTS_YET_SHOP_NOW_AND_ASK_FOR_YOUR_FIRST_ORDER:
      "لم تقم بأي طلبات حتى الآن.. تسوق الآن و أطلب طلبك الأول",
    SHOPPING_DRESSES: "تسوق الأثواب",
    IN_AANTZAR_HAWALA: "طلب غير مكتمل",
    READY_FOR_PICK_UP: "جاهز للإستلام",
    DESIGNER: "مصمم",
    CLOTH: "القماش",
    COLLAR: "الياقة",
    SLEEVES: "الكُم",
    STARLINGS: "الجبزور",
    ADDITIONS: "الحشوة",
    SIZES: "المقاس",
    TWO_PIECES: "قطعتين",
    PIECES: "قطع",
    SMALL: "صغير",
    LARGE: "كبير",
    MEDUIM: "متوسط",
    CHOOSE_MEASUREMENT_BEFORE_OTHER_OPTIONS: "برجاء اختيار ملف مقاسات أو اختيار ترزي لتتمكن من استكمال تصميم الثوب",
    CAN_NOT_CANCEL_THE_REQUEST: "لا يمكن إلغاء الطلب",
    YOU_SURE_YOU_WANT_TO_CANCEL_THE_ORDER_NUMBER:
      "أنت على وشك إلغاء طلب رقم",
    CANCELLATION_POLICY_APPLICATIONS: "يرجى الاطلاع والموافقة على سياسة الإلغاء:",
    CANCEL_ORDER_POLICY_1_TITLE: "1- يمكنك الإلغاء قبل الدفع.",
    CANCEL_ORDER_POLICY_2_TITLE: "2- إذا لم يتم الدفع خلال 48 ساعة يتم إلغاء الطلب تلقائياً.",
    CANCEL_ORDER_POLICY_3_TITLE: "3- لا يمكنك إلغاء الطلبات بعد البدء بعملية الإنتاج.",
    CANCEL_ORDER_POLICY_4_TITLE: "4- يمكنك الاسترجاع والتبديل خلال 3 أيام مع تحمل قيمة الشحن وسلامة المنتج.",
    CANCEL_ORDER_POLICY_5_TITLE: "5- يتم تحويل المبلغ المدفوع خلال 14 يوم عمل كحد أقصى.",
    APPLICATION_NO_ENTERED: "لقد دخل الطلب رقم",
    IN_PRODUCTION_AND_YOU_CAN_NOT_CANCEL_NOW_STAGE_IF_YOU_ARE_EXPERIENCING_ANY_PROBLEM_PLEASE_CONTACT_61648111100:
      "في مرحلة الإنتاج ولا يمكنك إلغاؤه الآن. إذا كنت تواجه أي مشكلة يرجى الاتصال على ",
    HOME_DELIVERY: "توصيل منزلي",
    YOU_DO_NOT_EXIT_THIS_SECTION_AFTER_SELECTIONS:
      "لم تقم بإنهاء اختيارات هذا القسم بعد",
    NOTES: "ملاحظات",
    YOU_CAN_WRITE_ANY_NOTES_OR_ADDONS_HERE:
      "يمكنك كتابه أي ملاحظات أو إضافات هنا ",
    PLEASE: "من فضلك",
    TO_BE_ABLE_TO_ATTACH_FILES: "لكي تتمكن من إرفاق ملفات",
    THE_FIRST_MODIFIED_DRESS_OITOB: "تعديل ثوب أيتوب الأول",
    THIS_PRICE_INCLUDES_THE_PRICE_OF_THE_ORIGINAL_DRESS_WITH_ADDITIONS:
      "هذا السعر يتضمن السعر الأصلى للثوب مع الإضافات",
    ADDING_TO_CART: "إضافة إلى العربة",
    COMPLETE_THE_AMENDMENT: "أكمل التعديل",
    YES_ADD_TO_CART: "نعم أضف إلى العربة",
    ARE_YOU_SURE_YOU_COMPLETE_ALL_THE_AMENDMENTS_TO_THE_DRESS:
      "هل أنت متأكد من إتمام جميع التعديلات على الثوب؟",
    GARY_ADD_TO_CART: "جارى الإضافة إلى العربة",
    UPLOADING_FILES: "جارى رفع الملفات",
    DID_NOT_WORK: "لم تنجح",
    THERE_IS_A_LINE_IN_THIS_LINK_AWANK_YOU_NEED_TO_LOG_IN:
      "هناك خطا في هذا الرابط أو أنك تحتاج تسجيل الدخول",
    YES_ADD_TO_CART_ADJUSTMENT: "نعم أضف التعديل إلى العربة",
    OK: "اوك",
    LOOKING_IN_THE_QUESTIONS: "ابحث في الأسئلة",
    THE_DESIGN_OF_A_NEW_DRESS: "تصميم ثوب جديد",
    MODIFY_DRESS: "تعديل الثوب",
    YOU_DO_NOT_EXIT_SELECTIONS_AFTER_THE_CLOTH:
      "لم تقم بإنهاء اختيارات القماش بعد",
    YOU_DO_NOT_EXIT_SELECTIONS_AFTER_COLLAR:
      "لم تقم بإنهاء اختيارات الياقة بعد",
    YOU_DO_NOT_EXIT_SELECTIONS_SLEEVES_AFTER:
      "لم تقم بإنهاء اختيارات الكُم بعد",
    YOU_DO_NOT_EXIT_SELECTIONS_AFTER_STARLINGS:
      "لم تقم بإنهاء اختيارات الجبزور بعد",
    YOU_DO_NOT_EXIT_OPTIONS_ADDITIONS_AFTER:
      "لم تقم بإنهاء اختيارات الحشوة بعد",
    THE: "ال",
    MORE_OF: "مزيد من",
    DID_NOT_COMPLETE_THE_BASIC_CHOICES_FOR_THIS_DRESS_PLEASE_END_THE_FIRST_AMENDMENTS:
      "لم تقم بإكمال الاختيارات الأساسية لهذا الثوب . يرجى إنهاء التعديلات أولاً",
    OUT_OF_THE_EDIT_MODE: "الخروج من وضع التعديل",
    DO_YOU_WANT_TO_GET_OUT_OF_THE_EDIT_MODE_YOU_WILL_HARNESS_ALL_THE_CHANGES_YOU_HAVE_MADE_AND_WILL_NOT_BE_ABLE_TO_RETRIEVE_IT_AGAIN:
      "هل تريد الخروج من وضع التعديل؟ سوف تخسر كل التعديلات التى قمت بها و لن تتمكن من استرجاعها مرة أخرى",
    I_WANT_TO_GO_OUT: "أريد الخروج",
    I_WANT_TO_STAY: "أريد البقاء",
    DESIGN: "تصميم",
    NEW_DRESS: "ثوب جديد",
    THERE_IS_NO_PRODUCTS_IN_THIS_CATEGORY: "لا يوجد منتجات في هذا التصنيف",
    ADD_A_NEW_CARD: "اضافة بطاقة جديدة",
    LAST_UPDATE: "آخر تحديث",
    CM: "سم",
    MODIFY: "تعديل",
    COMPLETE: "غير مكتمل",
    SAVE_THE_FILE_SIZES: "حفظ ملف المقاسات",
    NEW_SIZE: "مقاس جديد",
    OUT_OF_THE_SITUATION_TAKE_MEASUREMENTS: "الخروج من وضع أخذ المقاسات",
    REMEMBER_MQASATY_FILE: "حفظ ملف مقاساتي",
    NAME_FILE_SIZES: "اسم ملف المقاسات",
    FILE_SIZES_HAVE_BEEN_ADDED: "تم إضافة ملف مقاسات",
    ACCOUNT_SETTINGS: "إعدادت الحساب",
    MY_MEASUREMENTS: "مقاساتي",
    ADD_NEW_MEASUREMENT_FILE: "إضافة ملف مقاسات جديد",
    YOU_DO_NOT_HAVE_ANY_SIZES_I_ADD_YOUR_SIZE_NOW:
      "لا يوجد لديك أي مقاسات .. قم بإضافة مقاسك الأول الآن.",
    STARTS_FROM: "يبدأ من",
    WITHOUT_SHIPPING_AND_TAILOR: "بدون الشحن و الترزي",
    PAYMENT_CONFIRMATION: "تأكيد الدفع",
    SIGN_IN_WITH_TWITTER: "دخول عبر تويتر",
    BASIC_SIZE: "المقاس الأساسي",
    SET_AS_BASIC: "اختيار كأساسي",
    DO_YOU_WANT_TO_GET_OUT_OF_THE_SITUATION_TAKE_MEASUREMENTS_YOU_WILL_HARNESS_ALL_THE_CHANGES_YOU_HAVE_MADE_AND_WILL_NOT_BE_ABLE_TO_RETRIEVE_IT_AGAIN:
      "هل تريد الخروج من وضع أخذ المقاسات؟ سوف تخسر كل التعديلات التى قمت بها و لن تتمكن من استرجاعها مرة أخرى",
    OR: "أو",
    NO_SEARCH_RESULTS_MATCH_YOUR_ENTERED_TEXT:
      "لا توجد نتائج بحث تطابق النص الذي أدخلته",
    THE_ORDER_NUMBER: "تم إلغاء الطلب رقم",
    SUCCESSFULLY_CANCELLED: "بنجاح",
    YOU_HAVE_DELETED: "تم حذف",
    YOUR_MONEY_WILL_BE_REFUNDED_WITHIN_DAYS_FROM_THE_DATE_OF_THE_DAY:
      "سوف تسترد أموالك في فترة ١٤ يوم من تاريخ اليوم. لأي استفسار آخر يرجى الإتصال على",
    RESTORATION_OF_FUNDS: "2- أستعاده الأموال",
    DISCOUNT: "1- الخصم",
    COMPLETE_THE_PAYMENT_PROCESS: "إكمال عملية الدفع",
    UNFORTUNATELY_THIS_CODE_IS_INCORRECT_PLEASE_MAKE_SURE_THE_CODE_AND_TRY_AGAIN:
      " للأسف هذا الكود غير صحيح, يرجى التأكد من الكود و المحاولة مرة أخرى",
    AFTER_DISCOUNT: "بعد الخصم",
    YOU_DO_NOT_HAVE_CURRENT_ORDERS: "ليس لديك طلبات حالية",
    YOU_DO_NOT_HAVE_PREVIOUS_ORDERS: "ليس لديك طلبات سابقة",
    YOU_DO_NOT_HAVE_CANCELED_ORDERS: "ليس لديك طلبات ملغية",
    YOU_DO_NOT_HAVE_ORDERS: "ليس لديك طلبات",
    THE_PASSWORD_YOU_ENTERED_IS_CAFE_MUST_BE_YOUR_PASSWORD_CONSISTING_OF_8_DIGITS_OR_CHARACTERS:
      "كلمة المرور التى أدخلتها غير كافيه, يجب أن تكون كلمة المرور مكونه من 8 أرقام أو أحرف",
    NO_MORE_PRODUCTS: "لا يوجد مزيد من المنتجات",
    YOU_MUST_CHOOSE_A_SPECIFIC_SIZE_BEFORE_ADDING_TO_RICKSHAW:
      "لابد من اختيار مقاس محدد قبل الإضافة إلى العربة",
    SELECTED_SIZES_IS_INCOMPLETE_FILE_MUST_BE_COMPLETED_OR_CHOOSE_ANOTHER_SIZE:
      "ملف المقاسات المختار غير مكتمل .. لابد من استكماله أو اختيار مقاس آخر",
    LESS_SIZE: "أقل مقاس",
    TOP_SIZE: "أعلى مقاس",
    CM: "سم",
    STEPS_TAKEN_SIZE: "خطوات أخذ المقاس",
    SOME_CUSTOMERS_PREFER_TO_INCREASE_1_CM_LENGTH_DRESS_MORE_COMFORTABLE:
      "بعض العملاء يفضلون زيادة 1 سم لمزيد من الراحة",
    ADVICE: "ملاحظة",
    PRESS_THE_PLAY_BUTTON_TO_SEE_HOW_TO_TAKE_THE_SIZE:
      "قم بالضغط على زر التشغيل لمشاهدة كيفية اخذ المقاس.",
    PLEASE_ENTER_A_VALUE_OF: "يرجى إدخال قيمة من",
    TO: "إلى",
    BACK_TO_SHOPPING_CART: "الرجوع إلى عربة التسوق",
    SHOE_SIZE_SHOULD_BE_BETWEEN_41_TO_45:
      "مقاس الحذاء يجب أن يكون بين 41 إلى 45",
    NAME_THE_FILE_SIZES_TO_REACH_IT_FASTER:
      "قم بتسمية ملف المقاسات لتصل إليه بشكل أسرع",
    ENTER_THE_NAME_OF_SIZE: "أدخل اسم المقاس",
    YOU_MUST_COMPLETE_SELECTION_OF_SIZES: "يجب إكمال اختيار المقاسات",
    AFTER_DISCOUNT_APIECE: "القطعة الواحدة بعد الخصم",
    SHOULD_NOT_CONTAIN_SPECIAL_CHARACTERS:
      "الاسم لا ينبغي أن يحتوي على أحرف خاصة أو أرقام",
    SHIPPING_SERVICE_NOT_AVAILABLE:
      "عفواً خدمة الشحن غير متوفرة في منطقتك، إذا كنت ترغب في تغيير منطقة التوصيل اضغط",
    HERE: "هنا",
    CONTACTITHOOB_MESSAGE: "تم إرسال الرسالة بنجاح",
    CONTACTITHOOB_CONTENT: "سيتم التواصل معك في أقرب وقت ممكن",
    PRIVACY_POLICY: ' سياسة الخصوصية ',
    PULL_BACK_POLICY: ' سياسة الإسترجاع ',
    DISCOUNT_COUPON: 'كوبون الخصم',
    COUPON_DISCOUNT: ' خصم كوبون',
    TERMS_AND_CONDITIONS: 'الشروط والأحكام',
    COUPON_DISCOUNT_VALUE: 'قيمة خصم الكوبون',
    COUPON_DISCOUNT: ' خصم الكوبون',
    DELIVERY_POLICY: ' سياسة التوصيل ',
    SUBSCRIPE_TO_OUR_NEWS_LETTER: ' إشترك فى نشرتنا الإخبارية ',
    SUBSCRIPE_TO_OUR_NEWS_LETTER_TO_RECIEVE_EVERY_NEW: ' ليصلك جديدنا iThoob إنضم لمجتمع',
    ENTER_YOUR_EMAIL_AND_PHONE_AND_WE_WILL_CONTACT_YOU: ' أدخل بريدك الإلكترونى ورقم الجوال وسوف نتواصل معك ',
    CUSTOMER_SERVICE_EMAIL: 'إيميل خدمة العملاء',
    SUBSCRIPE_NOW: "إشترك الأن",
    PAY_ON_DELIVERY: "الدفع عند الإستلام",
    PAY_WITH_CREDIT_CARD: "الدفع بالبطاقة الإئتمانية ",
    PAY_THROUGH_BANK_TRANSFARE: "الدفع بحوالة بنكية",
    PLEASE_ADD_CORRECT_COUPON_CODE: "من فضلك أدخل كود صحيح",
    ADD_COUPN_CODE: " أضف كوبون",
    REQUEST_TAILOR: "أطلب الخياط",
    THE_NAIGHBORHOOD: "الحى",
    THE_STREET: "الشارع",
    NERABY_MILESTONE:"معلم قريب",
    OTHER_DETAILS:"تفاصيل أخرى",
    THE_SUITABLE_TIME:"الوقت المناسب ",
    FROM: " من ",
    TO:" إلى ",
    CONFIRM_REQUEST:" تأكيد الطلب",
    PLEASE_ENTER_THE_REGION_NAME: "من فضلك أدخل إسم المنطقة",
    PLEASE_ENTER_THE_NAIGHBORHOOD_NAME: "من فضلك أدخل إسم الحى",
    PLEASE_ENTER_THE_STREET_NAME: "من فضلك أدخل إسم الشترع",
    PLEASE_ENTER_THE_SUITABLE_TIME: "من فضلك أدخل الوقت المناسب",
    COUPON_DISCOUNT_FOR_THOOB: "خصم كوبون على الثياب",
    COUPON_DISCOUNT_FOR_THOOB_AND_SHOES: "خصم كوبون على الاكسسوارات والأحذية",
    PIECES_NUMBER_HENT: "سيتم إضافة مبلغ 50 ريال  مصاريف انتقالات للعدد اقل من 3 قطع !",
    PIECES_NUMBER: "عدد القطع",
    WE_WILL_CONTACT_YOU_AS_SOON_AS_POSSIBLE: "سيتم التواصل معك فى اقرب وقت",
    UNDO: "تراجع",
    REDO: "إعادة",
    BACK: "رجوع",
    INSTALLMENT_WITH_TABBY: " تقسيط مع tabby",
  },
  en: {
    FAV_LANG: "Language",
    FAV_LANGUAGE: "Select Language",
    SHOPPING_CART: "Cart",
    SR: "SR",
    UNDO: "Undo",
    REDO: "Redo",
    BACK: "Back",
    INSTALLMENT_WITH_TABBY: "Installment with Tabby",
    PIECES_NUMBER: "Pieces Number",
    WE_WILL_CONTACT_YOU_AS_SOON_AS_POSSIBLE: "We will contact you as soon as possible",
    PIECES_NUMBER_HENT: "An amount of 50 riyals, transportation fees, will be added to the number less than 3 pieces",
    COUPON_DISCOUNT_FOR_THOOB: "Coupon discount for Clothes",
    COUPON_DISCOUNT_FOR_THOOB_AND_SHOES: "Coupon discount for shoes & accessories",
    REQUEST_TAILOR: "Request a Tailor",
    THE_NAIGHBORHOOD: "The Naghborhood",
    THE_STREET: "The Street",
    NERABY_MILESTONE:"Neraby Milestone",
    OTHER_DETAILS:"Other Details",
    THE_SUITABLE_TIME:"The Suitable Time",
    CONFIRM_REQUEST:" Request Confirm",
    FROM: "From",
    TO:"To",
    PLEASE_ENTER_THE_REGION_NAME: "Please Enter The Region Name",
    PLEASE_ENTER_THE_NAIGHBORHOOD_NAME: "Please Enter The Naighborhood Name",
    PLEASE_ENTER_THE_STREET_NAME: "Please Enter The Street Name",
    PLEASE_ENTER_THE_SUITABLE_TIME: "Please Enter The Suitable Time",
    PLEASE_ADD_CORRECT_COUPON_CODE: "Please Add Correct Coupon Code",
    ADD_COUPN_CODE: " Add Coupon Code",
    PAY_ON_DELIVERY: "Cash On Delivery",
    PAY_WITH_CREDIT_CARD: "Pay With Credit Card",
    PAY_THROUGH_BANK_TRANSFARE: "Pay Through bank transfer",
    SUBSCRIPE_TO_OUR_NEWS_LETTER: "Suscribe To Our News Letter",
    SUBSCRIPE_TO_OUR_NEWS_LETTER_TO_RECIEVE_EVERY_NEW:  "Join iThoob Community To Recieve Every New",
    ENTER_YOUR_EMAIL_AND_PHONE_AND_WE_WILL_CONTACT_YOU: "Enter Your Email And Phone Number And We Will Contact You",
    CUSTOMER_SERVICE_EMAIL: 'Customer Service Email',
    SUBSCRIPE_NOW: "Subscripe Now",
    DELIVERY_POLICY: ' Delivery Policy',
    COUPON_DISCOUNT_VALUE: 'Coupon Discount Value',
    COUPON_DISCOUNT: 'Coupon Discount',
    TERMS_AND_CONDITIONS: ' Terms And Conditions',
    TOTAL_PRODUCTS: "Total Products",
    COUPON_DISCOUNT: 'Coupon Discount',
    THERE_ARE_NO_PRODUCTS_IN_THE_SHOPPING_CART:
      "There are no products in the cart",
    FIRST_ITHOOB_CLOTH: "First IThoob Cloth",
    GO_TO_PAY: "Checkout",
    TO_THE_SHOPPING_CART: "View Cart",
    BACK_TO_THE_SHOPPING_CART: "Back To The Cart",
    MAIN: "Home",
    PAYMENT_AND_RECEIPT: "Payment & Delivery",
    PAYMENT: "Payment",
    CONFIRMATION: "Confirmation",
    ARE_YOU_SURE_YOU_WANT_TO_COMPLETE_THE_REQUEST:
      "Are you sure you want to complete the order?",
    YES_COMPLETE_THE_ORDER: "Yes, complete the order",
    NO: "No",
    DELIVERY_METHOD: "Delivery Method",
    PAYMENT_METHOD: "Payment Method",
    DELIVERY_TO_HOME: "Home Delivery",
    RECEIVING_FROM_BRANCH: "Branch Delivery",
    ADDRESS: "Address ",
    BRANCH_DETAILS: "Branch details",
    BRANCH_ADDRESS: "Branch Address",
    WORKING_HOURS_BRANCH: "Branch Working Hours",
    BRANCH_NUMBER: "Branch Number",
    YOUR_ORDER_NUMBER: "Your order number",
    DONE_SUCCESSFULLY: "has been successful",
    YOU_WILL_BE_COMPLETED_REGISTER_YOUR_TEXT_MESSAGE_AFTER_TWO_DAYS:
      "Your register will be completed with text message after two days",
    COMPLETE_SHOPPING: "Continue Shopping",
    CONTINUED_REQUEST: "Follow up on your order",
    ORDER_SUMMARY: "Order Summary",
    SHIPPING: "Shipping",
    YOU_WILL_DETERMINE_THE_COST_OF_SHIPPING_BASED_ON_YOUR_AREA_AND_YOUR_ADDRESS:
      "Cost will be determined based on your area and address",
    PARTNERS_CODE: "Partner Discount",
    I_HAVE_OBTAINED_A_DISCOUNT_VALUES: "You have a",
    HIGHEST_DISCOUNT_WILL_BE_APPLIED: "Highest discount will be applied",
    SHIPPING_IS_A_COMPREHENSIVE_AND_COST_TAILOR:
      "discount, not including the shipping and tailor costs",
    PERMANENT_DISCOUNT: "Permanent discount",
    PERMANENT_DISCOUNT_WORTH: "Permanent discount with",
    BEING_A_PERMANENT_PARTNERS_ANY_GOWN: "as you are one of ithoob partners",
    YOU_CAN_NOT_LEAVE_THE_TITLE_BOX_BLANK:
      "You cannot leave it blank.",
    THERE_IS_ONE_OR_MORE_UNAVAILABLE_ITEMS: "There is one or more unavailable items in your cart",
    NOT_AVAILABLE_ITEM: "This item is no longer available",
    THIS_PRODUCT_IS_SOLD_OUT: "This product is sold out!",
    THIS_PRODUCT_IS_OUT_OF_STOCK: "Sold Out",
    GO_TO_PAYMENT: "Checkout",
    BANK_TRANSFER: "Bank transfer",
    THE_ORDER_WILL_BE_CONFIRMED_TWO_DAYS_AFTER_THE_ARRIVAL_OF_THE_HAWALA_BANKING_US:
      "The order will be confirmed after two days of the bank transfer",
    ACCOUNT_NUMBER: "Account number",
    THE_RECEIPT: "Delivery",
    RECEIVING_DATE: "Delivery Date",
    YOUR_REQUEST_WILL_BE_READY_FOR_PICK_UP:
      "Your request will be ready for pick-up",
    TAILOR: "Tailor",
    WILL_CALL_YOU_ONE_OF_OUR_REPRESENTATIVES_TO_SET_A_DATE_FOR_TAKING_MQASATK_HOME:
      "One of our team will call you to arrange an appointment to take measurements at the home",
    ANY_DRESS_IS_A_SAUDI_BRAND_GIVES_YOU_A_PROVEN_FACT_NAK_LONG_TIME_AGO_IS_THAT_THE_READABLE_CONTENT_OF_A_PAGE_SILAA_NATURALLY:
      "A brand that distinguishes a man's thoob, to combine the elegance and originality",
    ITHOOB_RIGHTS_RESERVED: "Copyright iThoob 2020",
    JZL_RIGHTS_RESERVED: "Copyright iThoob 2020",
    CONNECT_WITH_US: "Contact Us",
    ABOUT_ITHOOB: "About iThoob",
    ABOUT_JZL: "About iThoob",
    MEASUREMENTS_TABLE: "Measurements Table",
    FAQ: "FAQs",
    PERSONAL_INFORMATION: "Personal Information",
    MEASUREMENTS: "My Measurements",
    MY_ORDERS: "My Orders",
    LOG_OUT: "Logout",
    DESIGNED_YOUR_DRESS: "Design your Thoob",

    YOU_MUST_ENTER_THE_NEW_PASSWORD: "Please enter new password",
    THE_PASSWORD_YOU_ENTERED_IS_CAFE_MUST_BE_YOUR_PASSWORD_CONSISTING_OF_8_DIGITS_OR_LETTERS:
      "The password should consist of 8 digits or more",
    CHANGE_PASSWORD: "Change Password",
    NEW_PASSWORD: "New Password",
    COUNTRY: "Country",
    REGION: "Region",
    ACCOUNT_SUCCESSFULLY_CREATED: "Account created successfully",
    YOU_ARE_A_PARTNER_OF_ANY_DISCERNING_DRESS_AND_SO_YOU_WILL_ENJOY_A_PERMANENT_DISCOUNT_TO_ANY_OF_THE_PRODUCTS_OF_ANY_DRESS_VALUES:
      "You are one of iThoob special customers and you will enjoy a permanent discount for any product with",
    START_SHOPPING_NOW: "Start shopping now",
    PLEASE_ENTER_YOUR_PASSWORD: "Please enter your password",
    SHOULD_NOT_BE_LESS_THAN_THE_NUMBER_OF_CHARACTERS_NAME_3:
      "Name shouldn't be less than 3 characters",
    PLEASE_WRITE_YOUR_CORRECT_EMAIL_AND_TRY_AGAIN:
      "Please enter a valid email",
    EMAIL_SEEMS_SHORT_PLEASE_ENTER_A_VALID_EMAIL:
      "Email seems short ... Please enter a valid email",
    PLEASE_ENTER_YOUR_PHONE_NUMBER: "Please enter your phone number",
    THE_PHONE_NUMBER_IS_NOT_ENOUGH_PLEASE_ENTER_THE_NUMBERS_8_OR_MORE:
      "The mobile is short. Please enter 8 numbers or more",
    PLEASE_ENTER_NUMBERS_ONLY: "Please enter numbers only",
    CREATE_A_NEW_ACCOUNT: "Create a new account",
    FORGOT_YOUR_PASSWORD: "Forgot your password?",
    E_MAIL: "Email",
    PASSWORD: "Password",
    OPTIONAL: "optional",
    CREATE_ACCOUNT: "Create Account",
    THE_NAME: "Name",
    MOBILE: "Mobile",
    MOBILE_HINT: "Example: 00966987654321",
    SIGN_IN_WITH_FACEBOOK: "Sign in with Facebook",
    THIS_E_MAIL_IS_INCORRECT_PLEASE_MAKE_SURE_OF_IT_AND_TRY_AGAIN:
      "Please enter a valid email",
    PASSWORD_RECOVERY: "Reset Password",
    SIGN_IN_WITH_GOOGLE: "Sign in with Google",
    RECOMMENDED: "Recommended",
    PLEASE_ENTER_THE_NUMBER_OR_YOUR_EMAIL:
      "Please enter the number or your Email.",
    EMAIL_FORMAT_IS_INCORRECT_MUST_BE_COORDINATION:
      "Email format is incorrect, it must be example@example.com",
    NO_MOBILE_IS_INCOMPLETE: "Mobile number is incomplete",
    EMAIL_IS_INCOMPLETE: "Email is incomplete",
    THE_PASSWORD_IS_NOT_ENOUGH_MUST_BE_PASSWORD_COMPOSED_OF_8_DIGITS_OR_LETTERS:
      "The password should consist of 8 digits or more",
    DO_YOU_WANT_TO_SET_UP_AN_ACCOUNT_AND_RESTORE_ALL_MQASATK_AND_PREVIOUS_REQUESTS_HAVE_ANY_DRESS:
      "Do you want to set up an account and restore all your previous measurements and orders in ithoob?",
    YOU_DO_NOT_HAVE_AN_ACCOUNT_CREATE_AN_ACCOUNT:
      "Don't have an account? Join now",
    SIZE: "Size",
    THIS_FILE_IS_INCOMPLETE_MUST_COMPLETE_THE_FILE_BEFORE_PURCHASE:
      "The file is incomplete, you should complete it before checkout",
    ADD_FILE_FORMAT: "Add Measurements File",
    I_WANT_TO_TAKE_SIZE_TAILOR_HOME: "I want to take the measurements",
    THE_EXTRA_COST_STARTING_FROM: "There will be an additional cost starting from",
    BY_REGION: "depending on the region",
    LOADING: "Loading",
    //khadrah
    BEST_SELLER: "Best Seller",
    DRESS_DESIGNER: "Designed Thoob",
    RATE: "Edited",
    SPECIAL_SIZE: "Special size",
    DO_NOT_CHOOSE_SIZE: "Measurement not selected",
    CHOOSE_SIZE: "Select Measurement",
    I_WANT_TO_TARZI: "Tailor Requested",
    MODIFY: "Edit",
    CHANGING_THE_SIZE: "Edit measurement",
    DELETE: "Delete",
    ONE_PIECE: "one piece",
    EDIT_THE_DRESS: "Edit your Thoob",
    DELETED: "Deleted",
    SUCCESSFULLY_CANCELLED: "is successfully cancelled",
    ARE_YOU_SURE_YOU_WANT_TO_DELETE: "Are you sure you want to delete",
    OF_YOUR_SHOPPING_CART: "From your Shopping Cart?",
    YEAH: "Yes",
    EDIT_SIZE: "Edit Measurment",
    ANY_TOP_PARTNERS: "iThoob Partners",
    PARTNERS_SCHEDULE: "Partners Table",
    USE_YOUR_COMPANY_EMAIL_TO_GET_PARTNER_DISCOUNT: "Write your company email to get the discount code",
    ENTER: "Enter",
    THE_COST_TAILOR: "Tailor Cost",
    YOU_WILL_DETERMINE_THE_COST_TARAZI_BASED_ON_YOUR_AREA_AND_YOUR_ADDRESS:
      "The tailor cost will be determined based on your area and address",
    TOTAL_PRODUCTS: "Total Products",
    DISCOUNT_PERCENTAGE: "discount percentage",
    PARTNERS: "Partners",
    THE_MOST_COMMON_QUESTIONS: "Frequently Asked Questions",
    ACCOUNT_SETTINGS: "Account Settings",
    MY_PROFILE: "Personal Information",
    YOU_MUST_FILL_IN_THE_PASSWORD: "Enter your current and new password",
    THE_NEW_PASSWORD_YOU_ENTERED_IS_CAFE_MUST_BE_YOUR_PASSWORD_CONSISTING_OF_8_DIGITS_OR_CHARACTERS:
      "The password you entered must be 8 digits or characters",
    CURRENT_PASSWORD: "Current Password",
    PASSWORD_CHANGED_SUCCESSFULLY: "Password changed successfully",
    MY_PERSONAL: "Personal Information",
    BASIC_INFORMATION: "Basic Information",
    PLEASE_ENTER_YOUR_NAME: "Please enter your name",
    NAME_YOU_MUST_BE_BETWEEN_3_TO_50_CHARACTERS:
      "Name must be between 3 to 50 characters",
    DO_YOU_WANT_TO_CHANGE_YOUR_PASSWORD: "Do you want to change your password?",
    PRESS_HERE: "Change",
    CONTACT_INFO: "Contact Info",
    TITLE_OPTIONAL: "Address (optional)",
    TITLE_MUST_BE_BETWEEN_3_TO_100_CHARACTERS:
      "Address must be between 20 to 100 characters",
    YOUR_INFORMATION_HAS_BEEN_UPDATED_SUCCESSFULLY:
      "Your information has been updated successfully",
    SAVING_INFORMATION: "Save Information",
    THE_FIRST_DESIGNED_YOUR_DRESS: "Design your first Thoob",
    ADD_TO_CART: "Add to Cart",
    ADD_TO_CART_NOTIFICATION: "Added To Cart",
    THE_COLOR: "Color",
    DRESS_ACCESSORIES: "Thoob Accessories",
    A_MESSAGE_WAS_SENT_TO_YOUR_EMAIL: "A message has been sent to your email",
    A_MESSAGE_WAS_SENT_TO_YOUR_PHONE: "A message has been sent to your phone",
    PLEASE_ENTER_THE_CODE_SENT_TO_YOUR_EMAIL_TO_COMPLETE_THE_REGISTRATION_PROCESS:
      "Please enter the code sent to your email to complete the registration",
    PLEASE_ENTER_THE_CODE_SENT_TO_YOUR_PHONE_TO_COMPLETE_THE_REGISTRATION_PROCESS:
      "Please enter the code sent to your phone to complete the registration",
    SEND_CODE_AGAIN: "Send code again",
    CODE: "Code",
    PLEASE_ENTER_THE_CODE_SENDER_PHONE:
      "Please enter the code sent to your  phone",
    PLEASE_ENTER_THE_CODE_IN_FULL: "Please enter the code in full",
    REGISTER_BY_EMAIL: "Sign up by Email",
    HAVE_AN_ACCOUNT_BEFORE: "Have an account before? ",
    OR: "or",
    QUANTITY: "Quantity",
    SHOP_NOW: "Shop now",
    VIEW_MORE: "View more",
    LATEST: "Latest",
    RECOMMENDED_A: "Recommended",
    PRODUCT_DISPLAY: "View Product",
    //mai
    CONTACT_US: "Contact Us",
    THE_MESSAGE: "Message",
    SEND: "Send",
    OH_PLEASE_ADD_YOUR_NAME: "Oh! Please add your name",
    OH_THIS_LOOKS_SO_SHORT_TO_BE_YOUR_NAME:
      "Oh! This looks so short to be your name",
    OH_PLEASE_ADD_A_VALID_EMAIL_ADDRESS:
      "Oh! Please add a valid email address.",
    OH_THIS_LOOKS_SO_SHORT_TO_BE_YOUR_EMAIL:
      "Oh! This looks so short to be your email",
    OH_YOU_MOBILE_NUMBER_SHOULD_BE_ONLY_DIGITS:
      "Oh! you mobile number should be only digits",
    OH_THIS_LOOKS_SO_SHORT_TO_BE_YOUR_MOBILE_NUMBER:
      "Oh! This looks so short to be your mobile number",
    YOU_FORGET_TO_WRITE_YOUR_MESSAGE: "You forget to write your message",
    SIZES_TABLE: "Measurements Table",
    CANCELLING_ORDER: "Cancel Order",
    MY_REQUESTS: "My Orders",
    YOU_CAN_FOLLOW_YOUR_ORDERS_FROM_HERE:
      "You can track your orders from here",
    CURRENT_APPLICATIONS: "Current Orders",
    ALL_APPLICATIONS: "All Orders",
    PREVIOUS_APPLICATIONS: "Previous Orders",
    ORDERS_CANCELED: "Cancelled Orders",
    APPLICATION_NO: "Order No.",
    ORDER_CANCELED: "Cancelled",
    NEW_ORDER: "New",
    PRODUCTION_STAGE: "Production",
    DELIVERY: "Delivered",
    READY_BRANCH: "Pickable",
    RECEIVED: "Delivered",
    CHARGED: "Charged",
    DETAILS: "Order Details",
    DISPLAY_ADJUSTMENTS: "View Edits",
    STARTS_FROM: "Starts from",
    THE_TOTAL_EXPECTED: "Expected Total",
    SHIPPING__PAYMENT: "Shipping & Payment",
    PAYMENT_METHOD: "Payment Method",
    SHIPPING_METHOD: "Shipping Method",
    NOT_ANY_REQUESTS_YET_SHOP_NOW_AND_ASK_FOR_YOUR_FIRST_ORDER:
      "You have no orders yet. Shop now and place for your first order",
    SHOPPING_DRESSES: "Shopping Athwab",
    IN_AANTZAR_HAWALA: "Waiting banking transfer",
    READY_FOR_PICK_UP: "Pickable",
    DESIGNER: "Designed",
    CLOTH: "Fabric",
    COLLAR: "Collar",
    SLEEVES: "Sleeves",
    STARLINGS: "Gebzour",
    ADDITIONS: "The padding",
    SIZES: "Measurements",
    TWO_PIECES: "Two pieces",
    PIECES: "pieces",
    SMALL: "small",
    LARGE: "large",
    MEDUIM: "meduim",
    CHOOSE_MEASUREMENT_BEFORE_OTHER_OPTIONS: "Please select your measurement/size or select a sizeman to continue customizing your thoob",
    CAN_NOT_CANCEL_THE_REQUEST: "You can't cancel this order",
    YOU_SURE_YOU_WANT_TO_CANCEL_THE_ORDER_NUMBER:
      "You're about to cancel order number",
    CANCELLATION_POLICY_APPLICATIONS: "Please read and agree to the cancellation policy:",
    CANCEL_ORDER_POLICY_1_TITLE: "1- You can cancel before paying",
    CANCEL_ORDER_POLICY_2_TITLE: "2- If the payment is not made in 48 hours, the order will be canceled automatically",
    CANCEL_ORDER_POLICY_3_TITLE: "3- Orders cannot be canceled after starting the production process",
    CANCEL_ORDER_POLICY_4_TITLE: "4- You can return and exchange within 3 days with cost of the shipping and product safety",
    CANCEL_ORDER_POLICY_5_TITLE: "5- The amount paid will be transferred within a maximum of 14 working days",
    APPLICATION_NO_ENTERED: "Order No.",
    IN_PRODUCTION_AND_YOU_CAN_NOT_CANCEL_NOW_STAGE_IF_YOU_ARE_EXPERIENCING_ANY_PROBLEM_PLEASE_CONTACT_61648111100:
      "in production now, and you can't cancel it. If you are facing any problem, please contact",
    HOME_DELIVERY: "home delivery",
    YOU_DO_NOT_EXIT_THIS_SECTION_AFTER_SELECTIONS:
      "You do not finish this section ",
    NOTES: "Notes",
    YOU_CAN_WRITE_ANY_NOTES_OR_ADDONS_HERE:
      "You can write any notes or add-ons here",
    PLEASE: "please",

    LOG_IN: "Login",
    TO_BE_ABLE_TO_ATTACH_FILES: "To be able to attach files",
    THE_FIRST_MODIFIED_DRESS_OITOB: "The first modified Thoob Oitob",
    THIS_PRICE_INCLUDES_THE_PRICE_OF_THE_ORIGINAL_DRESS_WITH_ADDITIONS:
      "This price includes the price of the original Thoob with additions",
    ADDING_TO_CART: "Adding to the cart",
    COMPLETE_THE_AMENDMENT: "Complete the adjustment",
    YES_ADD_TO_CART: "Yes, add to the cart",
    ARE_YOU_SURE_YOU_COMPLETE_ALL_THE_AMENDMENTS_TO_THE_DRESS:
      "Are you sure you have completed all adjustments on the thoob?",
    GARY_ADD_TO_CART: "Adding to Cart",
    UPLOADING_FILES: "Uploading files",
    DID_NOT_WORK: "Don't success",
    THERE_IS_A_LINE_IN_THIS_LINK_AWANK_YOU_NEED_TO_LOG_IN:
      "There is an error in this link OR you need to log in",
    YES_ADD_TO_CART_ADJUSTMENT: "Yes Add Amedments to Cart",
    OK: "OK",
    LOOKING_IN_THE_QUESTIONS: "Search in questions",
    THE_DESIGN_OF_A_NEW_DRESS: "The design of a new thoob",
    MODIFY_DRESS: "Modify Thoob",
    YOU_DO_NOT_EXIT_SELECTIONS_AFTER_THE_CLOTH:
      "You didn't complete all Fabric options yet",
    YOU_DO_NOT_EXIT_SELECTIONS_AFTER_COLLAR:
      "You didn't complete all Collar options yet",
    YOU_DO_NOT_EXIT_SELECTIONS_SLEEVES_AFTER:
      "You didn't complete all Sleeves options yet",
    YOU_DO_NOT_EXIT_SELECTIONS_AFTER_STARLINGS:
      "You didn't complete all Gebzour options yet",
    YOU_DO_NOT_EXIT_OPTIONS_ADDITIONS_AFTER:
      "You didn't complete all Padding options yet",
    THE: "the",
    MORE_OF: "More of",
    DID_NOT_COMPLETE_THE_BASIC_CHOICES_FOR_THIS_DRESS_PLEASE_END_THE_FIRST_AMENDMENTS:
      "You didn't complete all selections for this Thoob. Please complete it first!",
    OUT_OF_THE_EDIT_MODE: "Exiting from adjustment mode",
    DO_YOU_WANT_TO_GET_OUT_OF_THE_EDIT_MODE_YOU_WILL_HARNESS_ALL_THE_CHANGES_YOU_HAVE_MADE_AND_WILL_NOT_BE_ABLE_TO_RETRIEVE_IT_AGAIN:
      "Do you want to exit the adjustment mode? You will lose all the adjustments you have made and you will not be able to get them back",
    I_WANT_TO_GO_OUT: "Needing to exit",
    I_WANT_TO_STAY: "Needing to stay",
    DESIGN: "Design",
    NEW_DRESS: "New Thoob",
    THERE_IS_NO_PRODUCTS_IN_THIS_CATEGORY:
      "there is no products in this category",
    ADD_A_NEW_CARD: "Add a new card",
    LAST_UPDATE: "Last update",
    CM: "cm",
    MODIFY: "Edit",
    COMPLETE: "Complete",
    SAVE_THE_FILE_SIZES: "Save Measurements File",
    NEW_SIZE: "New File",
    OUT_OF_THE_SITUATION_TAKE_MEASUREMENTS:
      "Exiting the measurement mode",
    REMEMBER_MQASATY_FILE: "Save my measurement file",
    NAME_FILE_SIZES: "Measurements File Name",
    FILE_SIZES_HAVE_BEEN_ADDED: "Measurements file",
    ACCOUNT_SETTINGS: "Account Settings",
    MY_MEASUREMENTS: "My Measurements",
    ADD_NEW_MEASUREMENT_FILE: "Add New Measurements File",
    YOU_DO_NOT_HAVE_ANY_SIZES_I_ADD_YOUR_SIZE_NOW:
      "You do not have any measurement file . Add your first file now.",
    STARTS_FROM: "Starts from",
    WITHOUT_SHIPPING_AND_TAILOR: "Without shipping and Tailor",
    PAYMENT_CONFIRMATION: "Place Order",
    SIGN_IN_WITH_TWITTER: "Sign in with Twitter",
    BASIC_SIZE: "Default Size",
    SET_AS_BASIC: "Make Default",
    DO_YOU_WANT_TO_GET_OUT_OF_THE_SITUATION_TAKE_MEASUREMENTS_YOU_WILL_HARNESS_ALL_THE_CHANGES_YOU_HAVE_MADE_AND_WILL_NOT_BE_ABLE_TO_RETRIEVE_IT_AGAIN:
      "Do you want to exit the measurement mode? You will lose all the adjustments you have made and you will not be able to get them back",
    OR: "OR",
    NO_SEARCH_RESULTS_MATCH_YOUR_ENTERED_TEXT:
      "No search results match your entered text",
    THE_ORDER_NUMBER: "Your order number",
    SUCCESSFULLY_ADDED: "is successfully added",
    SUCCESSFULLY: "successfully",
    YOU_HAVE_DELETED: "You've deleted",
    YOUR_MONEY_WILL_BE_REFUNDED_WITHIN_DAYS_FROM_THE_DATE_OF_THE_DAY:
      "Your money will be refunded within 14 days. For any other inquiry please contact us",
    RESTORATION_OF_FUNDS: "2. Restoration of funds",
    DISCOUNT: "1. Discount",
    COMPLETE_THE_PAYMENT_PROCESS: "Complete the payment process",
    UNFORTUNATELY_THIS_CODE_IS_INCORRECT_PLEASE_MAKE_SURE_THE_CODE_AND_TRY_AGAIN:
      "Code is incorrect. Please enter correct code and try again",
    AFTER_DISCOUNT: "After Discount",
    YOU_DO_NOT_HAVE_CURRENT_ORDERS: "You do not have current orders",
    YOU_DO_NOT_HAVE_PREVIOUS_ORDERS: "You do not have previous orders",
    YOU_DO_NOT_HAVE_CANCELED_ORDERS: "You do not have cancelled orders",
    YOU_DO_NOT_HAVE_ORDERS: "You do not have orders",
    THE_PASSWORD_YOU_ENTERED_IS_CAFE_MUST_BE_YOUR_PASSWORD_CONSISTING_OF_8_DIGITS_OR_CHARACTERS:
      "The password should consist of 8 digits or more",
    NO_MORE_PRODUCTS: "No more products",
    YOU_MUST_CHOOSE_A_SPECIFIC_SIZE_BEFORE_ADDING_TO_RICKSHAW:
      "You should select a size before adding to cart",
    SELECTED_SIZES_IS_INCOMPLETE_FILE_MUST_BE_COMPLETED_OR_CHOOSE_ANOTHER_SIZE:
      "Selected measurement is an incomplete, you should complete it or choose another size",
    LESS_SIZE: "Less size",
    TOP_SIZE: "Top Size",
    CM: "cm",
    STEPS_TAKEN_SIZE: "Steps taken size",
    SOME_CUSTOMERS_PREFER_TO_INCREASE_1_CM_LENGTH_DRESS_MORE_COMFORTABLE:
      "Some clients prefer an increase of 1 cm for more comfort",
    ADVICE: "Note",
    PRESS_THE_PLAY_BUTTON_TO_SEE_HOW_TO_TAKE_THE_SIZE:
      "Press the play button to see how to take the size.",
    PLEASE_ENTER_A_VALUE_OF: "Please enter a value of",
    TO: "to",
    BACK_TO_SHOPPING_CART: "Back to Shopping Cart",
    SHOE_SIZE_SHOULD_BE_BETWEEN_41_TO_45:
      "Shoe size should be between 41 to 45",
    NAME_THE_FILE_SIZES_TO_REACH_IT_FASTER:
      "Name your Measurements File to reach it faster",
    ENTER_THE_NAME_OF_SIZE: "File name",
    YOU_MUST_COMPLETE_SELECTION_OF_SIZES:
      "You should complete selection of measurements",
    AFTER_DISCOUNT_APIECE: "Price after discount",
    SHOULD_NOT_CONTAIN_SPECIAL_CHARACTERS:
      "The name should not contain special characters or numbers",
    SHIPPING_SERVICE_NOT_AVAILABLE:
      "Sorry, shipping service is not available in your region, if you want to change the delivery area, click",
    HERE: "here",
    CONTACTITHOOB_MESSAGE: "The message has been sent successfully",
    CONTACTITHOOB_CONTENT: "We will contact you as soon as possible",
    PRIVACY_POLICY: 'Privacy Policy',
    PULL_BACK_POLICY: 'Pull Back Policy',
    DISCOUNT_COUPON: 'Discount Coupon '
  }
};
export function getStringVal(x, txt) {
  let lang = x ? "ar" : "en";
  return strings[lang][txt];
}
