//categories actions
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";
export const GET_CATEGORIES_FAIL = "GET_CATEGORIES_FAIL";
export const SET_ACTIVE_MENU = "SET_ACTIVE_MENU";

//breadcrumb list actions
export const UPDATE_BREADCRUMB_SUCCESS = "UPDATE_BREADCRUMB_SUCCESS";

//home actions
export const GET_HOME_PRODUCTS_SUCCESS = "GET_HOME_PRODUCTS_SUCCESS";
export const GET_HOME_PRODUCTS_FAIL = "GET_HOME_PRODUCTS_FAIL";
export const GET_HOME_SECTIONS_SUCCESS = "GET_HOME_SECTIONS_SUCCESS";
export const GET_HOME_SECTIONS_FAIL = "GET_HOME_SECTIONS_SUCCESS";

//banner actions
export const GET_BANNER_SUCCESS = "GET_BANNER_SUCCESS";
export const GET_BANNER_FAIL = "GET_BANNER_FAIL";

//product list actions
export const GET_PRODUCT_LIST_SUCCESS = "GET_PRODUCT_LIST_SUCCESS";
export const GET_PRODUCT_LIST_FAIL = "GET_PRODUCT_LIST_FAIL";
export const UPDATE_PAGE_INDEX = "UPDATE_PAGE_INDEX";
export const UPDATE_CALLING_API_STATUS_WHILE_SCROLLING =
  "UPDATE_CALLING_API_STATUS_WHILE_SCROLLING";
export const RESET_PRODUCT_LIST_SUCCESS = "RESET_PRODUCT_LIST_SUCCESS";

//product details actions
export const GET_PRODUCT_DETAILS_SUCCESS = "GET_PRODUCT_DETAILS_SUCCESS";
export const GET_PRODUCT_DETAILS_FAIL = "GET_PRODUCT_DETAILS_FAIL";
export const GET_MORE_PRODUCTS_SUCCESS = "GET_MORE_PRODUCTS_SUCCESS";
export const GET_MORE_PRODUCTS_FAIL = "GET_MORE_PRODUCTS_FAIL";
export const UPDATE_QUANTITY = "UPDATE_QUANTITY";
export const GET_DEFAULT_IDS = "GET_DEFAULT_IDS";
export const ADD_SELECTED_ID = "ADD_SELECTED_ID";
export const UPDATE_MAX_QUANTITY = "UPDATE_MAX_QUANTITY";
export const UPDATE_LOADER = "UPDATE_LOADER";
export const UPDATE_SCROLLING_LOADER = "UPDATE_SCROLLING_LOADER";

export const UPDATE_COLOR = "UPDATE_COLOR";
export const TOGGLE_PRODUCT_STATUS = "TOGGLE_PRODUCT_STATUS";

//measurements guide action
export const GET_MEASUREMENT_SUCCESS = "GET_MEASUREMENT_SUCCESS";
export const GET_MEASUREMENT_FAIL = "GET_MEASUREMENT_FAIL";

// profile action
export const GET_Profile_Info_SUCCESS = "GET_Profile_Info_SUCCESS";
export const GET_Profile_Info_FAIL = "GET_Profile_Info_FAIL";
export const UPDATE_Profile_Info_SUCCESS = "UPDATE_Profile_Info_SUCCESS";
export const UPDATE_Profile_Info_FAIL = "UPDATE_Profile_Info_FAIL";
export const CHANG_PASSWORD_SUCCESS = "CHANG_PASSWORD_SUCCESS";
export const CHANG_PASSWORD_FAIL = "CHANG_PASSWORD_FAIL";
export const DELETE_MASSAGE = "DELETE_MASSAGE";

// my cart actions
export const GET_CART_ITEMS_SUCCESS = "GET_CART_ITEMS_SUCCESS";
export const GET_CART_ITEMS_FAIL = "GET_CART_ITEMS_FAIL";

export const UPDATE_QUANTITY_SUCCESS = "UPDATE_QUANTITY_SUCCESS";
export const UPDATE_QUANTITY_FAIL = "UPDATE_QUANTITY_FAIL";

// export const UPDATE_EDIT_SIZE_DISPLAY_STATUS = "UPDATE_EDIT_SIZE_DISPLAY_STATUS";

export const UPDATE_SIZE_SUCCESS = "UPDATE_SIZE_SUCCESS";
export const UPDATE_SIZE_FAIL = "UPDATE_SIZE_FAIL";

export const GET_COLORS_SUCCESS = "GET_COLORS_SUCCESS";
export const GET_COLORS_FAIL = "GET_COLORS_FAIL";

export const GET_EDITS_SUCCESS = "GET_EDITS_SUCCESS";
export const GET_EDITS_FAIL = "GET_EDITS_FAIL";

export const GET_CODE_SUCCESS = "GET_CODE_SUCCESS";
export const GET_CODE_FAIL = "GET_CODE_FAIL";

export const UPDATE_PARTNER_TABLE_DISPLAY_STATUS =
  "UPDATE_PARTNER_TABLE_DISPLAY_STATUS";

export const UPDATE_SELECTED_COLOR_ID = "UPDATE_SELECTED_COLOR_ID";
export const UPDATE_SELECETED_IDS = "UPDATE_SELECETED_IDS";

export const UPDATE_CUSTOMS_SUCCESS = "UPDATE_CUSTOMS_SUCCESS";
export const UPDATE_CUSTOMS_FAIL = "UPDATE_CUSTOMS_FAIL";

export const GET_DISCOUNT_SUCCESS = "GET_DISCOUNT_SUCCESS";
export const GET_DISCOUNT_FAIL = "GET_DISCOUNT_FAIL";

export const GET_CART_ITEMS_FROM_LOCAL_STORAGE =
  "GET_CART_ITEMS_FROM_LOCAL_STORAGE";
export const DELETE_ITEM_FROM_LOCAL_STORAGE = "DELETE_ITEM_FROM_LOCAL_STORAGE";

export const UPDATE_QUANTITY_FROM_LOCAL_STORAGE =
  "UPDATE_QUANTITY_FROM_LOCAL_STORAGE";

export const UPDATE_CUSTOMS_CONTAINER_RENDER =
  "UPDATE_CUSTOMS_CONTAINER_RENDER";

export const UPDATE_EDIT_SIZE_RENDER = "UPDATE_EDIT_SIZE_RENDER";

export const GET_PARTNERS_SUCCESS = "GET_PARTNERS_SUCCESS";
export const GET_PARTNERS_FAIL = "GET_PARTNERS_FAIL";
export const GET_CHECKOUT_DATA_SUCCESS = "GET_CHECKOUT_DATA_SUCCESS";
export const GET_CHECKOUT_DATA_FAIL = "GET_CHECKOUT_DATA_FAIL";
export const UPDATE_DELIVERY_METHOD = "UPDATE_DELIVERY_METHOD";
export const UPDATE_ADDRESS = "UPDATE_ADDRESS";
export const UPDATE_PAYMENT_METHOD = "UPDATE_PAYMENT_METHOD";
export const CONFIRM_PAYMENT_SUCCESS = "CONFIRM_PAYMENT_SUCCESS";
export const CONFIRM_PAYMENT_FAIL = "CONFIRM_PAYMENT_FAIL";
export const UPDATE_SHOW_CONFIRM_PAYMENT_POPUP =
  "UPDATE_SHOW_CONFIRM_PAYMENT_POPUP";
export const UPDATE_ORDER_SUCCEEDED_POPUP = "UPDATE_ORDER_SUCCEEDED_POPUP";
export const UPDATE_CUSTOMS_STATUS_ACTION = "UPDATE_CUSTOMS_STATUS_ACTION";
export const UPDATE_SIZE_FROM_LOCAL_STORAGE = "UPDATE_SIZE_FROM_LOCAL_STORAGE";
export const ADD_PARTNER_DISCOUNT_ID_TO_LOCAL_STORAGE =
  "ADD_PARTNER_DISCOUNT_ID_TO_LOCAL_STORAGE";
export const GET_PARTNER_DISCOUNT_FROM_LOCAL_STORAGE =
  "GET_PARTNER_DISCOUNT_FROM_LOCAL_STORAGE ";

export const GET_MEASUREMENT_LIST_SUCCESS = "GET_MEASUREMENT_LIST_SUCCESS";
export const GET_MEASUREMENT_LIST_FAIL = "GET_MEASUREMENT_LIST_FAIL";
export const UPDATE_DEFAULT_MEASUREMENT_SUCCESS =
  "UPDATE_DEFAULT_MEASUREMENT_SUCCESS";
export const UPDATE_DEFAULT_MEASUREMENT_FAIL =
  "UPDATE_DEFAULT_MEASUREMENT_FAIL";
export const RESET_DEFAULT_MEASUREMENT = "RESET_DEFAULT_MEASUREMENT";

export const UPDATE_DELETED_ITEM_ID = "UPDATE_DELETED_ITEM_ID";
export const UPDATE_DELETED_ITEM_INDEX = "UPDATE_DELETED_ITEM_INDEX";
export const UPDATE_DELETED_ITEM_TITLE = "UPDATE_DELETED_ITEM_TITLE";
export const UPDATE_DELETE_CONFIRMED_MODAL_DISPLAY =
  "UPDATE_DELETE_CONFIRMED_MODAL_DISPLAY";

export const UPDATE_SLUG = "UPDATE_SLUG";
// coupon actions
export const CHECK_FOR_COUPON = "CHECK_FOR_COUPON";
export const UPDATE_COUPON_SUCCESS = "UPDATE_COUPON_SUCCESS";
export const UPDATE_COUPON_FAILED = "UPDATE_COUPON_FAILED";

//add measurement
export const GET_ADD_MEASUREMENT_SUCCESS = "GET_ADD_MEASUREMENT_SUCCESS";
export const GET_ADD_MEASUREMENT_FAIL = "GET_ADD_MEASUREMENT_FAIL";
export const UPDATE_ACTIVE_ITEM_ID = "UPDATE_ACTIVE_ITEM_ID";
export const SAVE_MEASUREMENT_SUCCESS = "SAVE_MEASUREMENT_SUCCESS";
export const SAVE_MEASUREMENT_FAIL = "SAVE_MEASUREMENT_FAIL";
export const UPDATE_DATA_IS_CHANGED_STATUS = "UPDATE_DATA_IS_CHANGED_STATUS";
export const UPDATE_CONFIRMATION_MODAL = "UPDATE_CONFIRMATION_MODAL";
export const UPDATE_SIZE_NAME_MODAL = "UPDATE_SIZE_NAME_MODAL";
export const UPDATE_SUCCESS_MODAL = "UPDATE_SUCCESS_MODAL";
export const UPDATE_SIZE_FILE_NAME = "UPDATE_SIZE_FILE_NAME";
export const GET_MEASUREMENT_DETAILS_SUCCESS =
  "GET_MEASUREMENT_DETAILS_SUCCESS";
export const GET_MEASUREMENT_DETAILS_FAIL = "GET_MEASUREMENT_DETAILS_FAIL";

export const UPDSTE_ERR_MSG_STATUS = "UPDSTE_ERR_MSG_STATUS";
export const UPDATE_MEASUREMENTS_IS_COMPLATE_STATUS =
  "UPDATE_MEASUREMENTS_IS_COMPLATE_STATUS";
export const UPDATE_SIZE_STATUS = "UPDATE_SIZE_STATUS";

export const UPDATE_GET_CODE_STATUS_AND_GET_CODE_MESSAGE =
  "UPDATE_GET_CODE_STATUS_AND_GET_CODE_MESSAGE";
export const UPDATE_DISCOUNT_STATUS_AND_DISCOUNT_MESSAGE =
  "UPDATE_DISCOUNT_STATUS_AND_DISCOUNT_MESSAGE";
export const FROM_CART_TO_EDITCUSTOMS_STATUS =
  "FROM_CART_TO_EDITCUSTOMS_STATUS";
export const DELETE_CART_ITEMS_FROM_LOCAL_STORAGE =
  "DELETE_CART_ITEMS_FROM_LOCAL_STORAGE";
export const DELETE_PARTNER_DISCOUNT_FROM_LOCAL_STORAGE =
  "DELETE_PARTNER_DISCOUNT_FROM_LOCAL_STORAGE";
export const UPDATE_MEASUREMENT_ERR_MSG = "UPDATE_MEASUREMENT_ERR_MSG";

export const UPDATE_SUBMIT_STATUS = "UPDATE_SUBMIT_STATUS";

export const UPDATE_IS_LOADING_STATUS = "UPDATE_IS_LOADING_STATUS";

export const UPDATE_REDIRECT_TO_CHECKOUT = "UPDATE_REDIRECT_TO_CHECKOUT";

export const CLEAR_CART = "CLEAR_CART";

export const UPDATE_SHOES_SIZE_STATUS = "UPDATE_SHOES_SIZE_STATUS";

export const INITIAL_PRODUCT_LIST = "INITIAL_PRODUCT_LIST";

export const UPDATE_CARRUNT_VALUES = "UPDATE_CARRUNT_VALUES";

export const UPDATE_FROM_PRODUCT_DETAILS = "UPDATE_FROM_PRODUCT_DETAILS";

export const GET_FROM_PRODUCT_DETAILS = "GET_FROM_PRODUCT_DETAILS";

// request tailor typs
export const REQUEST_TAILOR_POPUP_STATUS = "REQUEST_TAILOR_POPUP_STATUS";
export const REQUEST_TAILOR_SUCCESS = "REQUEST_TAILOR_SUCCESS";
export const REQUEST_TAILOR_FAIL = "REQUEST_TAILOR_FAIL";
export const UPDATE_TAILOR_REQUESTED_MODAL_DISPLAY = "UPDATE_TAILOR_REQUESTED_MODAL_DISPLAY";

export const CHANGE_DELIVERY_ADDRESS = "CHANGE_DELIVERY_ADDRESS";
